apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: vertx
spec:
  template:
    metadata:
      annotations:
        # Target 1 request in-flight per pod.
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: docker.io/matzew/helloworld-vertx
          env:
          - name: TARGET
            value: "Eclipse Vert.x!"
