apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: event-display
spec:
  template:
    metadata:
      annotations:
        # Target 1 request in-flight per pod.
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: docker.io/matzew/event-display
