apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: wss-events-trigger
  namespace: default
spec:
  filter:
    sourceAndType:
      type: my.custom.event
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: event-display

